// STRINGS USED IN UI
const strings = {
  email: 'Email',
  password: 'Password',
  name: 'Name',
  //Login View
  loginTitle: 'LOG IN',
  passwordOption: 'Forgot Password?',
  notAccount: "Don't have an account?",
  register: 'Register now!',
  myProfile: 'My Profile',
  //Signup View
  signupTitle: 'SIGN UP',
  authPerson: 'Already an have account?',
  loginNow: 'Login now!',

  welcome: 'Welcome User!',
  heyUser: 'Hey User!',
  yourCart: 'Your Cart!',
  totalPrice: 'Total Price:',
  googleLogin: 'Continue with Google',
  or: 'or',
  authLogin: 'Authorized Login',
  // MeraDoc
  webniars: 'Webniars',
  blogs: 'Blogs',
  content:
    'Missed our webinars? No issues, we got you covered. Access all our webinars below & share them with your family, friends and colleagues.',
  watch: 'Watch our latest Healthcare Bytes',
  speakers: 'Our Speakers',
  jhon: 'Dr.John',
  detail: 'President NATHEALTH & Founder,Mahajan Imagining',
  williams: 'Dr.Williams',
  aditya: 'Dr.Aditya K',
  view: 'View',
  onBoarding: 'On-boarding pending!',
  answer:
    'Answer a few questions to get' + '\n' + 'the best customised program',
  completedPercent: '40% only completed',
  completeNow: 'Complete Now',
  subPlans: 'MeraDoc Subscription Plans',
  famCare: 'GIVE THE CARE YOUR FAMILY DESERVES',
  plan1: 'Unlimited free 24x7 consultations ',
  plan2: 'Entire Extended Family Coverage',
  plan3: 'Saving upto 25% on medicines',
  plan4:
    'Health Vaulty: One place fro all your and your family memebers past, present & future medical reports & history',
  plan5: 'Benefits are for entire extended family One family One Plan',
  knowMore: 'Know more',
  services: 'MeraDoc Services',
  physcian: 'Family Physician',
  phyDes:
    'pERSONALISED HEALTH SOLUTIONS FROM OUR IN-OUSE FAMILY PHYSICIANS FOR YOU & YOUR FAMILY ANYTIME ANYWHERE',
  specialist: 'Specialists',
  splDes:
    'Consult with Top Specialists across 20+Specialists for your Health Concerns',
  bookNow: 'Book NOW',
  checkOut: 'Check out our Webinars',
  loerom: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vulputate a mi at scelerisque. Quisque odio nunc, dapibus egestas nibh nec .',
  jhonDeo: 'Dr.John Deo',
  testimonial: 'Testimonials',
  instTrust: 'Institutions that trust us',
  partners: 'Our Alliance Partners',
  corporate: 'Corporate',
  wellness: 'Wellness',
  famSpl: 'Your family Specialist' + '\n' + 'a click away',
  bannerLoerem: 'Lorem ipsum dolor sit amet,' + '\n' + 'consectetur adipiscing elit',
  consult: 'Consult now',
  bannerTit: 'Not Keeping Well CAn Be an' + '\n' + 'Unsettling Feeling',
  bannerDes: 'Our doctor CAn help you' + '\n' + 'change that. Ask a question' + '\n' + 'and have our doctor’s answer.' + '\n' + 'Or read our blog fro quick tips' + '\n' + 'for a beteter lifestyle and to' + '\n' + 'stay healthy',
  read: 'Read Now',
  // from data
  relation: 'Relation',
  age: 'Age',
  dob: 'Date of Birth',
  bloodGroup: 'Blood Group',
  height: 'Height',
  weight: 'Weight',
  mobileNum: 'Mobile Number',
  gender: 'Gender',
  occupation: 'Occupation',
  address1: 'Addrees 1',
  name1: 'Name *',
  email1: 'Email *',
  address2: 'Addrees 2',
  city: 'City',
  pinCode: 'Pincode',
  dist: 'District',
  state: 'State',
  country: 'Country',
  latestPhoto: 'Latest Photo',
  upload: 'Upload',
  useMyCurLoc: 'Use my current loctaion',
  // Profile Screen
  familyTree: 'Family Tree',
  add: '+Add  member',
  addNew: 'Add new family member',

  // Consultation  Screen
  bookConsult: 'Book a Consultation',
  bookCons: 'Book Consultation',
  consultHours: '24*7 consultation with General Physician for any health concern',
  bookNowBtn: 'Book Now',
  bookSpl: 'Book a Specialist',
  splText: 'Consult India’s top specialists and super specialists online',
  upComing: 'My Upcoming Consultations',
  pastConsult: 'Past Consultations',
  consultation: 'Consultation',
  upComingConsultaion: 'Upcoming Consultation',
  pastConsultation: 'Past Consultation',
  userType: 'Single User',
  joinNow: 'Join Now',
  drName: "Dr.Usha",
  drId: '21658966adsss',
  drRole: 'General Physician',
  patientName: 'Patients Name: Jsj',
  dateAndTime: '6th Nov, 2020   2:30PM',
  completed: 'Completed',
  attended: 'Attended',
  missed: 'Missed',
  deleteAcc: 'Delete Account?',
  currentPassword: 'Current password',
  newPassword: 'New password',
  confirmPassword: 'Confirm password',
  changePassword: 'Change password',

  // book consultation
  genPhy: 'General Physician',
  language: 'Language',
  speakToDoc: 'Speak to a Doctor Now',
  speakCont: 'Get access to personalized healthcare services anytime, anywhere from our in-house doctors for you and your family',
  speakNow: 'Speak Now',
  selectDate: 'Select Convenient Date & Slot',
  date: '01/06/2021',
  prefferedSlot: 'Preffered slot',

  // Appointment Details
  appointmentDetails: 'Appointment Details',
  onlineCons: 'Online Consultation',
  dateCons: '6th Nov, 2020   2:30PM',
  docDetails: 'Doctor Details',
  exp: '5 years Exp',
  patientDetails: 'Patient Details',
  changePatient: 'CHANGE PATIENT',
  addFam: 'Add your family members to this Consult',
  resonForCons: 'Reason for Consultation',
  uploadReport: 'Upload Report',
  otherDetails: 'Order Details',
  consulCharge: 'Consultation Charges',
  bookingCharges: 'Booking Charges',
  tax: 'Tax',
  totalAmt: 'Total Amount',
applyCoupon:'apply Coupon',
  // WelcomeScreen
  welcomeTo: 'Welcome to MeraDoc',
  enterNumber: 'Enter your Mobile Number',
  account: 'Don’t have an account? Create Now',
  loginWith: 'Login with password',
  forgotPassword: 'Forgot password',

  //otp
  verify: 'Verify your number',
  sent: 'We have sent an One Time Password' + '\n' + 'to your mobile number',
  wait: 'please wait for 30s',

  // Button text
  verifyBtn: 'VERFIY',
  continue: 'CONTINUE',
  getStarted: 'GET STARTED',
};

const placeholders = {
  enterEmail: 'Enter your Email',
  enterPassword: 'Enter your Password',
  enterName: 'Enter name',
  enterMail1: 'Enter mail',
  enterRelation: 'Enter Relation',
  enterAge: 'Enter Age',
  enterOccupation: 'Enter Occupation (optional)',
  enterDob: 'Enter Date of Birth',
  enterNum: 'Enter Mobile Number',
  enterBloodGrp: 'Enter Blood Group',
  enterWeight: 'Enter Weight',
  enterHeight: 'Enter Height',

  enterAddress: 'Enter Address',
  enterDistrict: 'Enter District',
  enterCity: 'Enter City',
  enterPin: 'Enter pincode',
  enterState: 'Enter State',
  enterCountry: 'Enter Country'

};

export { strings, placeholders };
